version: '3.4'

services:

# application
  bankaccount-api:
    image: ${DOCKER_REGISTRY-}bankaccountpresentationapi
    container_name: bank_account
    build:
      context: .
      dockerfile: BankAccount.Presentation.Api/Dockerfile
    networks:
      - banknetwork
    environment:
      - MongoSettings_Connection=mongodb://root:password123@mongodb-primary:27017
      - MongoSettings_DatabaseName=BANK_ACCOUNT
    depends_on:
        - mongodb-primary
    links:
        - mongodb-primary

#database
  mongodb-primary:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_DATABASE: BANK_ACCOUNT
    ports:
      - 27017:27017
    volumes:
      - ./Volumes/MongoDB:/data/db
    networks:
      - banknetwork

# database management
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb-primary
    depends_on:
      -  mongodb-primary
    links:
      - mongodb-primary
    networks:
      - banknetwork


networks: 
    banknetwork:
      driver: bridge
 